### ISSUE TITLE
Potential duplicates in the covariate data.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid19.sgene.utla.rt#29]
I am seeing instances of the following duplication:

![Screenshot 2021-01-21 at 12 28 11](https://user-images.githubusercontent.com/20317649/105351272-3ed8d180-5be4-11eb-9504-c8a0c1acc8d4.png)

This appears to be coming from the sgene data:

```
sgene_by_utla %>% 
  filter(utla_name %in% "Derbyshire")

# A tibble: 24 x 7
   week_specimen nhser_name utla_name  utla_code week_infection prop_sgtf samples
   <date>        <chr>      <chr>      <chr>     <date>             <dbl>   <dbl>
 1 2020-10-05    Midlands   Derbyshire E10000007 2020-09-28       0.0288      452
 2 2020-10-05    North West Derbyshire E10000007 2020-09-28       0.0412       97
 3 2020-10-12    Midlands   Derbyshire E10000007 2020-10-05       0.0321      592
 4 2020-10-12    North West Derbyshire E10000007 2020-10-05       0.0231      130
 5 2020-10-19    Midlands   Derbyshire E10000007 2020-10-12       0.0146     1168
 6 2020-10-19    North West Derbyshire E10000007 2020-10-12       0.00541     185
 7 2020-10-26    Midlands   Derbyshire E10000007 2020-10-19       0.0217     1288
 8 2020-10-26    North West Derbyshire E10000007 2020-10-19       0.0165      243
 9 2020-11-02    Midlands   Derbyshire E10000007 2020-10-26       0.0283     1376
10 2020-11-02    North West Derbyshire E10000007 2020-10-26       0.00366     273
# … with 14 more rows
```

@sbfnk it looks to me like this from the raw sgtf data and doesn't look like its been controlled for elsewhere. Might be driving some of the odd findings.

**Comment by seabbs** [comment]
Dropping duplicates I see 1880 vs 2179 so its fraction of the data that is impacted.

**Comment by sbfnk** [comment]
I think that's from UTLAs that straddle multiple NHS regions - though slightly surprised it's that many. Will check.

**Comment by seabbs** [comment]
its by date as well right so far fewer UTLAs will have the issue.

**Comment by seabbs** [comment]
Hmm maybe this is actually broadly fine and doesn't induce any bias?
