### ISSUE TITLE
Provide interim/partial/final output

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid19.sgene.utla.rt#43]
Currently all output is gitignored meaning that anyone wanting to replicate the manuscripts needs to rerun the models. It would be nice if possible to provide saved versions of the results.

**Comment by sbfnk** [comment]
Good idea. They're all >100M in size. Any thoughts on the best way to include them?

**Comment by seabbs** [comment]
Dataverse - 😆 no. osf? Its a little cult-like and I've found it confusing in the past but is probably the best option I can think of. 

I've made a linked project here and will try and work out how to upload/download results (see here if fancying it: https://cran.r-project.org/web/packages/osfr/vignettes/getting_started.html)

Project: https://osf.io/h6e8n/
